# https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs
defaults: &defaults
  working_directory: ~/wk
  environment:
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    TERM: dumb

workflows:
  version: 2
  test_and_deploy:
    jobs:
        - test
        - deploy:
            filters:
                branches:
                    only: master
            requires:
                - test

version: 2
jobs:
    test:
        <<: *defaults

        docker:
            - image: circleci/php:7.1
            - image: tkuchiki/delayed-mysql
              environment:
                MYSQL_ALLOW_EMPTY_PASSWORD: yes
                MYSQL_ROOT_PASSWORD: ''
                MYSQL_DATABASE: circleci

        steps:
            - checkout

            - run:
                command: composer install

            - run:
                command: bin/disable-php-email

            - run:
                name: Wait for DB
                # preinstalled in circleci/* docker image
                command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s

            - run:
                command: bin/install-drupal

            - run:
                command: bin/start-webserver
                background: true

            - run:
                command: bin/wait-for-webserver

            - run:
                command: bin/behat

            - run:
                command: bin/stop-webserver

    deploy:
        <<: *defaults

        docker:
            - image: quay.io/pantheon-public/build-tools-ci:4.x

        steps:
            - checkout

            - run:
                command: composer install

            - run:
                command: cd drupal && ../bin/drush @wkweb.live ssh '(cd .. && git pull && composer install --no-dev)'

            - run:
                command: cd drupal && ../bin/drush @wkweb.live updatedb --yes && ../bin/drush @wkweb.stage cc all --yes

