# https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs
defaults: &defaults
  working_directory: ~/wk
  environment:
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    TERM: dumb

workflows:
  version: 2
  test_and_deploy:
    jobs:
        - test
        - deploy:
            filters:
                branches:
                    only: master
            requires:
                - test

version: 2
jobs:
    test:
        <<: *defaults

        docker:
            - image: wodby/drupal-php:7.0
            - image: circleci/mysql:5.7.24
              environment:
                - MYSQL_ALLOW_EMPTY_PASSWORD=true
                - MYSQL_ROOT_HOST=%

        steps:
            - checkout

            - run:
                command: composer install

            - run:
                command: echo 'sendmail_path=/bin/true' > /usr/local/etc/php/conf.d/sendmail-path.ini

            - run:
                command: bin/install-drupal

            - run:
                command: bin/start-webserver
                background: true

            - run:
                command: bin/wait-for-webserver

            - run:
                command: bin/behat

            - run:
                command: bin/stop-webserver

    deploy:
        <<: *defaults

        docker:
            - image: quay.io/pantheon-public/build-tools-ci:4.x

        steps:
            - checkout

            - run:
                command: composer install

            - run:
                command: cd drupal && ../bin/drush @wkweb.live ssh '(cd .. && git pull && composer install --no-dev)'

            - run:
                command: cd drupal && ../bin/drush @wkweb.live updatedb --yes && ../bin/drush @wkweb.stage cc all --yes

